# Generated by Django 5.0.3 on 2024-03-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonuser',
            old_name='grnder',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='commonuser',
            old_name='image',
            new_name='resume',
        ),
    ]
